title: Ion Trap
tagline: Trapped Ions Quantum Computer
owner: iontrapnet
link: https://iontrapnet.github.io
copyright: '&copy;&nbsp;<a href="https://iontrapnet.github.io">IonTrap-Net</a>'

permalink: pretty
markdown: kramdown
kramdown:
    input: GFM
    math_engine: mathjax
    auto_ids: true
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
#markdown: redcarpet
#redcarpet:
#    extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "highlight", "quote", "footnotes", "strikethrough", "with_toc_data"]
gems:
  - jekyll-sitemap
  
exclude: [README.md]
